package org.kapsathon.gonephishin;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "emails")
public class Email {
    private String id;
    private String sender;
    private String receiver;
    private String body;
    private String date;
    private String metadata;



    
 
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

	public void setId(String id) {
		this.id = id;
	}

	public String getSender() {
		return sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

    @DynamoDBAttribute
	public String getReceiver() {
		return receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

    @DynamoDBAttribute
	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

    @DynamoDBAttribute
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

    @DynamoDBAttribute
	public String getMetadata() {
		return metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

	@Override
	public String toString() {
		return "Email [body=" + body + ", date=" + date + ", id=" + id + ", metadata=" + metadata + ", receiver="
				+ receiver + ", sender=" + sender + "]";
	}

	public Email() {
	}

	public Email(String id, String sender, String receiver, String body, String date, String metadata) {
		this.id = id;
		this.sender = sender;
		this.receiver = receiver;
		this.body = body;
		this.date = date;
		this.metadata = metadata;
	}
 
    // standard setters/constructors
}